---
- name: "apt-get-update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install tools"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: install_packages

- name: "ensure nginx is at the latest version"
  apt: name=nginx state=latest
  tags: install_nginx

- name: "delete default nginx site"
  file:
    path: /etc/nginx/sites_enabled/default
    state: absent
  notify: restart nginx
  tags: configure_nginx

- name: "copy nginx site.conf"
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/hello.conf
    owner: root
    mode: '0644'
  notify: restart nginx
  tags: configure_nginx