---
- name: Apply common baseline configuration
  hosts: all
  become: yes
  roles:
    - role: common
      tags: common


- name: Install and configure Docker
  hosts: virtuals
  become: yes
  roles:
    - role: docker
      tags: docker

